### PR TITLE
noetic: pcl requires C++14

### PR DESCRIPTION
**Pull request by alexmillane**
Fixes the build on 20.04

### CODE REVIEW

**Comment by alexmillane** [comment]
@Jaeyoung-Lim Build is now triggered, however fails. This is due to a recent change in catkin_gprc. @tomlankhorst can you take a look at that?

**Comment by Jaeyoung-Lim** [comment]
@alexmillane Fixed in https://github.com/CogRob/catkin_grpc/pull/45

**Comment by alexmillane** [comment]
@Jaeyoung-Lim yeah I rolled back the version in our rosinstalls. Hopefully now things build. When your PR is merged over there, we can update the rosinstalls.

**Comment by alexmillane** [comment]
@Jaeyoung-Lim The build passes on github actions!!! Shall we pull the plug on Jenkins?

**Comment by Jaeyoung-Lim** [comment]
@alexmillane Yes please!

**Review by Jaeyoung-Lim — APPROVED** [review]

**Pull request merged**
