### PR TITLE
Make inheriting from simulation world possible

### PR DESCRIPTION
**Pull request by ToniRV**
This just allows users to be able to inherit from the simulation world to build their own simulation worlds :rocket:

### CODE REVIEW

**Comment by ToniRV** [comment]
@alexmillane Hi Alex, would it be possible to merge this?

**Comment by alexmillane** [comment]
Can one of the admins get this tested please :) @mfehr @helenol

**Comment by mfehr** [comment]
test this please

**Comment by ToniRV** [comment]
> Since you turned the sim world member into a pointer, you should check if it is a nullptr everywhere it is dereferenced, or at least once per function that is using it.

@mfehr Done! Thanks for the review Marius!

**Comment by mfehr** [comment]
ok to test

**Comment by ToniRV** [comment]
Yes! Although I think I did switch to CHECK(unique_ptr) in Kimera as well... bcs earlier versions of glog had this problem.

It's really up to you, I can change that to be consistent with voxblox, but, in principle, new users should not see any issues.

**Comment by ToniRV** [comment]
Friendly ping @mfehr :)

**Pull request merged**
