### PR TITLE
Add mutex to timer class.

### PR DESCRIPTION
**Pull request by fabianbl**
Timer class should be thread safe now.

### CODE REVIEW

**Comment by ZacharyTaylor** [comment]
The code looks good but I have one major concern with this. If the rest of the function in the thread does not need synchronization then we could get into the situation where the timer is actually forcing the threads to wait and bottlenecking performance.

I would maybe be of the opinion that we either remove any timers from inside concurrent sections or name them via the thread id so they are independent.

**Comment by mfehr** [comment]
I agree with @ZacharyTaylor, if we really want timers inside the threads, then the locking of this implementation is too coarse-grained and would lead to the effects described by Zach.

**Comment by fabianbl** [comment]
It's actually done similarly in maplab, but I can have a look at the performance later. In any case, this might solve ethz-asl/voxblox#92

**Comment by mfehr** [comment]
@ZacharyTaylor I think having separate entries for the thread id would be the right way, but not quite trivial how to implement it, IMO. Should we remove the timers in the concurrent sections for now?

**Comment by helenol** [comment]
I think we should just move timers outside the concurrent sections, which should solve all the problems here?

**Comment by mfehr** [comment]
I agree with @helenol, let's remove them, but then this PR doesn't do any harm. In case we miss a timer in a concurrent section at the very least it's not producing segfaults anymore. So let's remove them and merge this PR, wdyt?

**Pull request merged**
